<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2017-2024, Sreeni Viswanadha <sreeni@viswanadha.net>.
Copyright (c) 2024, Marc Mazas <mazas.marc@gmail.com>.
Copyright (c) 2017, Microsoft, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the names of of the copyright holders nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
-->
<project name="jscodegenerator"
         default="jar"
         basedir="."
         xmlns:artifact="antlib:org.apache.maven.artifact.ant"
>

  <property name="javacc-root" value="../../core" />
  <property name="java-src" value="src/main/java" />
  <property name="resources-src" value="src/main/resources" />
  <property name="target-folder" value="target" />
  <property name="javacc-jar" value="${javacc-root}/target/javacc.jar" />
  <property name="codgen-jar" value="${target-folder}/js-codegenerator.jar" />

  <target name="clean">
    <delete dir="classes" />
    <delete dir="lib" />
    <delete file="${codgen-jar}" />
  </target>

  <target name="compile" depends="clean">
    <mkdir dir="classes" />

    <copy todir="classes/templates">
      <fileset dir="${resources-src}/templates" />
    </copy>

    <copy todir="classes/META-INF/services">
      <fileset dir="${resources-src}/META-INF/services" />
    </copy>

    <javac srcdir="${java-src}"
           destdir="classes"
           debug="true"
           classpath="${javacc-jar}"
           includeantruntime='false'
    >
      <src path="${java-src}" />
      <src path="${resources-src}" />
    </javac>

  </target>

  <target name="jar" description="create javacc.jar">
    <antcall target="jar-nocompile" />
  </target>

  <target name="jar-nocompile">
    <mkdir dir="lib" />
    <antcall target="compile" />
    <jar jarfile="${codgen-jar}" basedir="classes" compress="true" />
  </target>

</project>
